---
functional:
  - Ведение рейтинга игроков по неделе/месяцу/всего и отображение на главной странице
  - Возможность просмотра истории баттлов.
  - Возможность просмотра повтора баттла.
  - Возможность выбора сложности баттла.
  - Возможность выбора языка для баттла.
  - Мультиязычность (русский и английский)
  - Поддержка всех популярных языков программирования
  - Уведомление о начале баттла
  - Возможность скрывать своё поле для кода от противника
  - Возможность просмотра баттла зрителям в режиме online
  - Возможность организации турниров и турнирной сетки
  - Возможность приглашать в баттл по ссылке / паролю
  - Возможность настройки таймера для баттла
  - Интеграция с приложениями для связи (Discord) для голосового соединения с соперником
  - Возможность переподключения участника к баттлу
  - После определения победителя должна быть возможность остаться в баттле и дописать код / ознакомиться с кодом
  - В лобби на каждом батле должна быть иконка, отображающая язык программирования, по которому будет баттл
  - В истории есть иконка напротив никнейма, указывающая на победителя баттла
  - Возможность перезапустить баттл с теми же участниками и параметрами, установленными в начале
  - Тренировочный режим
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве 
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла
